version: "3"

services:
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - CHANGE_SOURCE=${CHANGE_SOURCE}
    container_name: wim_nginx
    restart: always
    privileged: true
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - net-php

  php-fpm:
    build:
      context: ./php-fpm
      args:
        PHP_VERSION: ${PHP_VERSION}
        TZ: "$TZ"
        SWOOLE_VERSION: ${PHP71_SWOOLE_VERSION}
        XDEBUG_VERSION: ${PHP71_XDEBUG_VERSION}
    container_name: wim_php
    restart: always
    privileged: true
    volumes:
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${PHP_LOG_PATH}:/var/log/php
    expose:
      - "9000"
    networks:
      - net-php
      - net-mysql
      - net-redis
      - custom-net

  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    container_name: wim_mysql
    restart: always
    privileged: true
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - net-mysql

  redis:
    build: ./redis
    container_name: wim_redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - net-redis

networks:
  net-php:
  net-mysql:
  net-redis:
  custom-net:
    external:
      name: tesnet


